### PR TITLE
issue #88 Onboarding process of Ibrahim Kabir

### LINKED ISSUE #88: Onboarding process of Ibrahim Kabir
Update `dev-rel-docs` to accurately reflects the time consumption and add new exercises
### Tasks:
- [ ] Update time descriptions
- [ ] Incorporate new exercises
### Acceptance Criteria:
- The training should equip the developer with the skills necessary to work within the AI LAB's framework.
- The training should provide accurate time estimates for each module.

### PR DESCRIPTION
**Pull request by ibrahim-kabir**
Throughout Ibrahim Kabir's onboarding process, specific areas for improvement were noted:
1. **Training Time Descriptions Missing:** Backend training lacks adequate time descriptions.
2. **Exercises Gap in Training:** Backend training lacks PostgreSQL exercises.
### Tasks:
- [x] Update time descriptions.
- [x] Incorporate new PostgreSQL exercises into the training.
### Acceptance Criteria:
- The training should equip the developer with the skills necessary to work within the AI LAB's framework.
- The training should provide accurate time estimates for each module.
### Closes PR:
- Closes #88

### CODE REVIEW

**Comment by HsKocTets** [comment]
@rngadam The URL for: [Best Practices for Naming Git Branches](https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/naming-git-branches/) is no longer accessible (404). It seems they have migrated to this new [link](https://tilburgsciencehub.com/topics/automation/version-control/advanced-git/naming-git-branches/). This is causing a check failure. Do you approve the modification to the new link?

**Comment by rngadam** [comment]
> @rngadam The URL for: [Best Practices for Naming Git Branches](https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/naming-git-branches/) is no longer accessible (404). It seems they have migrated to this new [link](https://tilburgsciencehub.com/topics/automation/version-control/advanced-git/naming-git-branches/). This is causing a check failure. Do you approve the modification to the new link?

No need to ask for approval for this kind of obviously broken, obvious fixes kind of problems, especially since I have the opportunity to give feedback in the code review process.

**Comment by rngadam** [comment]
check fails so the priority is to make it pass.

**Comment by rngadam** [comment]
@ibrahim-kabir please prioritize finishing up ongoing work.

**Review by rngadam — APPROVED** [review]

**Pull request merged**
