### PR TITLE
Fixes #7 : Introduction Jolan Thomassin.

### LINKED ISSUE #7: Issue #7 : Introduction redat97
This is an issue created by Reda Tarzalt as part of the onboarding process.

### PR DESCRIPTION
**Pull request by JolanThomassin**
Adding Jolan Thomasin introduction.

### CODE REVIEW

**Review by rngadam — CHANGES_REQUESTED** [review]
see comment

**Review by rngadam — CHANGES_REQUESTED** [review]
have you checked how it renders?


image

**Comment by JolanThomassin** [comment]
Using only visual studio code I had not seen how the text would appear, I will change that right now.

**Comment by JolanThomassin** [comment]
Reda told me to use this extension to see how it would look in Git, and it works perfectly  
image

**Comment by rngadam** [comment]
there's no need to install an extension to view Markdown preview, VSC has preview builtin:

https://code.visualstudio.com/docs/languages/markdown#_markdown-preview

**Comment by rngadam** [comment]
also, you're referencing issue #7 , but issue #7 is redat97 issue intro. the instructions for the exercise should be updated to specify that you need to create your own issue.

**Comment by rngadam** [comment]
instead of fixing it by using preformatted text marker, please use a list

* a list
* such as this
* will separate by bullet points, each on their own lines.

**Pull request closed without merging**
