### PR TITLE
Clean out team members introduction

### LINKED ISSUE #66: Onboarding process of Thomas Cardin
Onboarding process of Thomas Cardin

### PR DESCRIPTION
**Pull request by ThomasCardin**
- Closes #66

### CODE REVIEW

**Review by rngadam — CHANGES_REQUESTED** [review]
Note that we actually want to change the process to add our profiles to the website ( repo ai-cfia-ia-acia.github.io) instead of the dev-rel-docs. Can you both update the process and move your and other team profiles there?

**Comment by ThomasCardin** [comment]
> Note that we actually want to change the process to add our profiles to the website ( repo ai-cfia-ia-acia.github.io) instead of the dev-rel-docs. Can you both update the process and move your and other team profiles there?

Good, thanks for the review. I have created this [pull request](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/pull/49). Let me know if you want me to remove the team introduction, including mine, from this repository!

**Comment by rngadam** [comment]
> Good, thanks for the review. I have created this [pull request](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/pull/49). Let me know if you want me to remove the team introduction, including mine, from this repository.

Yes I do want as we're moving it to the site.

**Comment by rngadam** [comment]
@ThomasCardin change this PR to clean out the introductions you've moved to the site.

**Review by rngadam — APPROVED** [review]

**Pull request merged**
