### PR TITLE
issue #58: Create TRAINING.md and import internal wiki content

### PR DESCRIPTION
**Pull request by rngadam**
closes issue #58 

* copy over list of public links from internal wiki
* tweak content to split into sections

### CODE REVIEW

**Review by JolanThomassin — APPROVED** [review]
There is no mention of ETL, I know there isn't one on the wiki. However, it could be interesting to add it. Otherwise, the text is the same as the wiki, so I can only approve.

**Review by melanie-fressard — APPROVED** [review]

**Review by leejaeka — APPROVED** [review]

**Review by k-allagbe — APPROVED** [review]
Looks good to me, from the backend perspective.

**Review by redat97 — COMMENTED** [review]
I would add [Creating a branch for an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue) as myself and @RussellJimmies both got told we needed to name our branch according to the issue

**Review by CFIALeronB — APPROVED** [review]

**Comment by rngadam** [comment]
@redat97 you left a comment instead of a review requiring changes.  please talk to Guy about how to complete PR reviews correctly.

I'm not addressing your suggestion as this would fit better into the doc we'll be moving out of the wiki explaining the process using the VSC Github plugin.

**Comment by redat97** [comment]
> @redat97 you left a comment instead of a review requiring changes.  please talk to Guy about how to complete PR reviews correctly.
> 
> 
> 
> I'm not addressing your suggestion as this would fit better into the doc we'll be moving out of the wiki explaining the process using the VSC Github plugin.

Yeah it was more of a suggestion that's why

**Comment by rngadam** [comment]
@redat97 then you should approve with comment

**Pull request merged**
