### PR TITLE
Rename 001-ailab-using-adr-template.md to 001-ailab-using-adr-templat…

### PR DESCRIPTION
**Pull request by nmeraihi**
…e.en-ca.md

The link in index wasn't working, wanted to make change and I noticed that we should keep consistency in naming fr-en

### CODE REVIEW

**Comment by rngadam** [comment]
@k-allagbe please validate and apply fix

**Review by k-allagbe — DISMISSED** [review]
Good catch.

**Comment by rngadam** [comment]
@k-allagbe what's going on here? you first approved and then commented that changes were still required in ADR but the PR is left hanging?

**Comment by k-allagbe** [comment]
@rngadam I'm working on the changes myself.

**Review by rngadam — APPROVED** [review]

**Pull request merged**
